### PR TITLE
Remove AdvancedReact course being re-recorded note

### PR DESCRIPTION
**Pull request by eagle6525**
The course is out and I'm excited to jump in!

### CODE REVIEW

**Comment by wesbos** [comment]
you are amazing! I didnt even think of this!

**Comment by eagle6525** [comment]
Looks like the site didn't update
image

I wanted to make sure I didn't cause an issue and it looks like an issue came up yesterday morning in this commit https://github.com/wesbos/wesbos/commit/5c651da0046b2cb2d5a46201d86018cefcdac38d blocking a deploy
image

I looked for a few minutes but was unable to easily reproduce the error below locally
image

**Comment by wesbos** [comment]
Oh shoot eh! Thank you for finding this - I just assumed It worked. My bad :) Trying a fix now

**Comment by wesbos** [comment]
All fixed! Thanks again

**Pull request merged**
