### PR TITLE
feat: Add gatsby-remark-embedder

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Add [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder)
- Replace CodePen embeds with pen links
- Replace Twitter embeds with tweet links
- Replace YouTube embeds with video links

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Ping @wesbos

**Comment by wesbos** [comment]
hey this is awesome - thanks a ton!

**Comment by MichaelDeBoey** [comment]
Always a pleasure to help out! 🙂

**Comment by MichaelDeBoey** [comment]
@wesbos It looks like something went wrong with deploying here 🤔😕

**Comment by klokie** [comment]
@MichaelDeBoey it looks like the plugin should be called `gatsby-remark-embedder` when referenced in `gatsby-config.js`. I had to change that to get it to compile.

**Comment by MichaelDeBoey** [comment]
Doh I wrote my own plugin's name wrongly! 😓

**Pull request merged**
