### PR TITLE
fix width for ultra-wide class in layout.js

### PR DESCRIPTION
**Pull request by osamamammar**
I think it is best to minimize it a bit. Because in this case, it makes reading difficult on large screens
and unpleasant to read, especially while reading articles that take the appearance of a blog.
the value I think it should be 930px or 800px something like that

### CODE REVIEW

**Comment by osamamammar** [comment]
I think a lot of people have the same opinion.

**Comment by wesbos** [comment]
Which layout does this effect?  Screenshot of before/after?

**Comment by osamamammar** [comment]
# First Layout Before:
before

before2

# After:
after
after2

# Second Layout Before:
notesBefore
notesBefore2

# After:
notesAfter
notesAfter2

**Comment by wesbos** [comment]
Oh man yeah this shouldn't be the case. Most of the blog is fixed at 800px wide. Let me dig a little more

**Comment by wesbos** [comment]
thanks for this! i just refactored it to not be too wide

**Pull request closed without merging**
