### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **30%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /src/components/mdxComponents/blackgrit.png | 219.45kb | 80.43kb | 63.35% |
| /src/posts/A Dead Simple intro to Destructuring JavaScript Objects/destrucuring-intro.png | 464.07kb | 193.54kb | 58.30% |
| /src/posts/My Animated GIF Workflow/ss-2016-02-18-at-12.53.48-PM.png | 84.98kb | 36.29kb | 57.30% |
| /src/components/mdxComponents/whitegrit.png | 154.69kb | 75.15kb | 51.42% |
| /src/posts/React for Beginners Re-Recorded again/Screen-Shot-2018-02-28-at-10.13.05-AM.png | 377.96kb | 184.37kb | 51.22% |
| /src/posts/cobalt2 -  a theme for Sublime Text/content.png | 155.72kb | 86.47kb | 44.47% |
| /src/posts/5 great visual tweaks for Sublime Text/ss-2013-01-08-at-11.28.45-AM.png | 5.51kb | 3.29kb | 40.32% |
| /src/posts/Mastering Markdown Mini Series/share@1x.png | 6,010.12kb | 3,599.19kb | 40.11% |
| /src/posts/ Git Hot Tips/ss-2016-03-10-at-9.09.24-AM.png | 24.84kb | 15.74kb | 36.65% |
| /src/posts/Rename  Destructure Variables in ES6/destrucuring-renaming.png | 291.30kb | 186.86kb | 35.85% |
| /src/posts/4 New String Methods in ES6 that you should know/4-new-string-methods.png | 312.26kb | 215.92kb | 30.85% |
| /src/posts-old/React-Context.png | 1,113.96kb | 770.36kb | 30.84% |
| /src/posts/Reacts New Context API Explained/React-Context.png | 1,113.96kb | 770.36kb | 30.84% |
| /src/posts/15 Slack Tips in 5 Minutes/15-tips.png | 351.70kb | 247.40kb | 29.66% |
| /src/posts/Speed Learning  How I consume and comprehend media at 2x/content.png | 111.42kb | 79.01kb | 29.09% |
| /src/posts/Announcing my CSS Grid Course/GRID-social-share.png | 3,059.16kb | 2,215.17kb | 27.59% |
| /src/posts/Flying a DJI Tello Drone with React and Nodejs/tello-art.png | 985.20kb | 723.58kb | 26.55% |
| /src/posts/React For Beginners Updated and Re-Recorded/facebook-share.png | 773.25kb | 575.58kb | 25.56% |
| /src/posts-old/thumb.png | 316.55kb | 236.84kb | 25.18% |
| /src/posts/Announcing Learn Redux/share.png | 2,149.92kb | 1,609.81kb | 25.12% |
| /src/posts/Announcing JavaScript30  A Free 30 day Vanilla JS Coding Challenge/JS3-social-share.png | 909.40kb | 684.33kb | 24.75% |
| /src/posts/The Breakout Email Management System/content.png | 177.39kb | 135.95kb | 23.36% |
| /src/posts/How do  - nth-child and nth-of-type really work/nth-child.png | 678.44kb | 521.94kb | 23.07% |
| /src/posts/ES6 for Everyone/es6-facebook-share.png | 476.70kb | 373.02kb | 21.75% |
| /src/posts/The Best Flexbox Resources/flexbox-resources.png | 830.25kb | 654.05kb | 21.22% |
| /src/posts/Sublime Text 3 -  First Look/content.png | 182.65kb | 148.47kb | 18.71% |
| /src/assets/images/logo.png | 249.16kb | 208.50kb | 16.32% |
| /src/posts/View CSS Colours in Sublime Text with GutterColor/content.png | 169.90kb | 142.67kb | 16.02% |
| /src/posts/View CSS Colours in Sublime Text with GutterColor/convert.png | 284.47kb | 245.69kb | 13.63% |
| /src/posts/Beginner JavaScript/Logo@2x-scaled.png | 556.80kb | 481.20kb | 13.58% |
| /src/posts/Beginner JavaScript/BJS-Social-Share-650x431.png | 122.51kb | 112.33kb | 8.31% |
| /src/posts/Announcing my CSS Grid Course/GRID-social-share-650x366.png | 219.34kb | 202.19kb | 7.82% |
| /src/posts/The Breakout Email Management System/breakout.jpg | 166.67kb | 157.30kb | 5.62% |
| /src/assets/images/handsome.jpg | 255.53kb | 241.97kb | 5.31% |
| /src/posts/Korean 27 Apple IPS Displays and a Macbook Pro -  Everything you need to know/photo_1-300x225.jpg | 18.91kb | 17.99kb | 4.88% |
| /src/posts/Announcing Learn Node/embeddable_25262a7f-5471-4dbb-8e88-c4d64a41f218.jpg | 59.31kb | 56.69kb | 4.41% |
| /src/assets/images/wes-and-scott.jpg | 241.31kb | 235.37kb | 2.46% |
| /src/posts/Uses/aeron.jpg | 100.11kb | 99.18kb | 0.92% |
| /src/assets/images/gatsby-image.jpg | 33.48kb | 33.22kb | 0.77% |
| | | | |
| **Total :** | **23,808.33kb** | **16,657.44kb** | **30.04%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in your full account).
It will automatically send PRs for image optimization 🙂

**Comment by wesbos** [comment]
Thanks! Doesn’t gatsby do this already? I’d like to keep the originals in the repo and have gatsby generate the compressed versions

**Comment by MichaelDeBoey** [comment]
Gatsby does this indeed (don't know in what amount tho), but this will make the repo a lot smaller too

**Comment by wesbos** [comment]
yeah makes sense but id like to keep the orignals in here

**Comment by MichaelDeBoey** [comment]
@wesbos The originals will be kept in here, just with a smaller size.
They're compressed Lossless, so no quality drop
https://imgbot.net/docs/#compression

**Comment by wesbos** [comment]
Ah I didn't realize it was lossless! Maybe I do want it then

**Comment by MichaelDeBoey** [comment]
Will create a new PR then 😉

**Pull request closed without merging**
